services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=vt_dev
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
# Will add Redis / Valkey later on.
